"""init schema

Revision ID: cb980d100f80
Revises:
Create Date: 2026-01-02 17:57:57.708104

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "cb980d100f80"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "documents",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("source", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("journal", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("published_date", sa.Date(), nullable=True),
        sa.Column("license", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_documents_source"), "documents", ["source"], unique=False)
    op.create_table(
        "runs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("kind", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("detail", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_runs_kind"), "runs", ["kind"], unique=False)
    op.create_table(
        "artifacts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("blob_key", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("kind", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("mime_type", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("sha256", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("bytes", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("blob_key", name="uq_artifacts_blob_key"),
    )
    op.create_index(op.f("ix_artifacts_blob_key"), "artifacts", ["blob_key"], unique=False)
    op.create_index(op.f("ix_artifacts_document_id"), "artifacts", ["document_id"], unique=False)
    op.create_index(op.f("ix_artifacts_kind"), "artifacts", ["kind"], unique=False)
    op.create_index(op.f("ix_artifacts_sha256"), "artifacts", ["sha256"], unique=False)
    op.create_table(
        "document_identifiers",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("scheme", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("value", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("scheme", "value", name="uq_identifier_scheme_value"),
    )
    op.create_index(
        op.f("ix_document_identifiers_document_id"),
        "document_identifiers",
        ["document_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_document_identifiers_scheme"), "document_identifiers", ["scheme"], unique=False
    )
    op.create_index(
        op.f("ix_document_identifiers_value"), "document_identifiers", ["value"], unique=False
    )
    op.create_table(
        "text_views",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("artifact_id", sa.Uuid(), nullable=False),
        sa.Column("view_kind", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("body_word_count", sa.Integer(), nullable=False),
        sa.Column("paragraph_count", sa.Integer(), nullable=False),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.Column("extractor_version", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["artifact_id"],
            ["artifacts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_text_views_artifact_id"), "text_views", ["artifact_id"], unique=False)
    op.create_index(op.f("ix_text_views_document_id"), "text_views", ["document_id"], unique=False)
    op.create_index(
        op.f("ix_text_views_extractor_version"), "text_views", ["extractor_version"], unique=False
    )
    op.create_index(op.f("ix_text_views_view_kind"), "text_views", ["view_kind"], unique=False)
    op.create_table(
        "chunks",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("text_view_id", sa.Uuid(), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("section", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("text", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("chunk_version", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["text_view_id"],
            ["text_views.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "text_view_id", "chunk_version", "ordinal", name="uq_chunk_view_ver_ord"
        ),
    )
    op.create_index(op.f("ix_chunks_chunk_version"), "chunks", ["chunk_version"], unique=False)
    op.create_index(op.f("ix_chunks_text_view_id"), "chunks", ["text_view_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_chunks_text_view_id"), table_name="chunks")
    op.drop_index(op.f("ix_chunks_chunk_version"), table_name="chunks")
    op.drop_table("chunks")
    op.drop_index(op.f("ix_text_views_view_kind"), table_name="text_views")
    op.drop_index(op.f("ix_text_views_extractor_version"), table_name="text_views")
    op.drop_index(op.f("ix_text_views_document_id"), table_name="text_views")
    op.drop_index(op.f("ix_text_views_artifact_id"), table_name="text_views")
    op.drop_table("text_views")
    op.drop_index(op.f("ix_document_identifiers_value"), table_name="document_identifiers")
    op.drop_index(op.f("ix_document_identifiers_scheme"), table_name="document_identifiers")
    op.drop_index(op.f("ix_document_identifiers_document_id"), table_name="document_identifiers")
    op.drop_table("document_identifiers")
    op.drop_index(op.f("ix_artifacts_sha256"), table_name="artifacts")
    op.drop_index(op.f("ix_artifacts_kind"), table_name="artifacts")
    op.drop_index(op.f("ix_artifacts_document_id"), table_name="artifacts")
    op.drop_index(op.f("ix_artifacts_blob_key"), table_name="artifacts")
    op.drop_table("artifacts")
    op.drop_index(op.f("ix_runs_kind"), table_name="runs")
    op.drop_table("runs")
    op.drop_index(op.f("ix_documents_source"), table_name="documents")
    op.drop_table("documents")
    # ### end Alembic commands ###
